server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo-transaction?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update