server:
  port: 8084

# Database Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo-transaction?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

#Logger Configuration
logging:
  level:
    com:
      spring:
        transaction:
          app: DEBUG
    org:
      hibernate:
        transaction: TRACE
      springframework:
        transaction: DEBUG
        orm:
          jpa:
            JpaTransactionManager: DEBUG


#  hikari:
#    minimum-idle: 5
#    maximum-pool-size: 20
#    auto-commit: true
#    isolation-level: TRANSACTION_READ_COMMITTED


